name: employee_management_mt_06022025
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  
  flutter_bloc: ^9.0.0
  get: ^4.6.6
  get_storage: ^2.1.1
  date_picker_plus: ^4.1.0
  fluttertoast: ^8.2.11
  intl: ^0.20.2
  dartz: ^0.10.1
  uuid: ^4.5.1
  flutter_slidable: ^4.0.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  freezed: ^2.5.8
  json_serializable: ^6.9.3

flutter:
  uses-material-design: true
  assets:
    - "assets/"
